title: yangmaoxin's 2017 Baidu IFE
url: https://ife.yangmaoxin.cn
enforce_ssl: ife.yangmaoxin.cn

show_downloads: true
google_analytics: UA-94111210-1

theme: jekyll-theme-leap-day

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
- README.md
